export const SEO_KEYWORD_TARGETS = [
  "TGO DevStudio",
  "TGO DevStudio Prime",
  "TGO software development",
  "TGO DevStudio Nigeria",
  "TGO DevStudio Lagos",
  "TGO DevStudio Abuja",
  "TGO DevStudio Port Harcourt",
  "TGO DevStudio software company",
  "TGO DevStudio engineering company",
  "TGO DevStudio full stack development",

  "full stack development company",
  "full stack software development company",
  "full stack software engineering company",
  "full stack developers",
  "full stack development services",
  "full stack engineering services",
  "custom software development company",
  "custom software development services",
  "software development company",
  "software engineering company",
  "software development agency",
  "software engineering agency",
  "software development studio",
  "software engineering studio",
  "digital product development company",
  "digital product development agency",
  "technology company",
  "technology consulting company",
  "technology consulting services",
  "software consulting company",
  "software consulting services",
  "IT consulting company",
  "IT consulting services",
  "digital transformation company",
  "digital transformation services",
  "technology solutions company",
  "technology solutions provider",
  "software solutions company",
  "software solutions provider",
  "enterprise software development",
  "enterprise software development company",
  "business software development",
  "business software solutions",
  "custom technology solutions",
  "custom digital solutions",
  "digital engineering company",
  "digital engineering services",
  "product engineering company",
  "product engineering services",
  "software product engineering",
  "software product development",

  "web development company",
  "web development agency",
  "website development company",
  "website development agency",
  "website design and development",
  "custom website development",
  "professional website development",
  "business website development",
  "corporate website development",
  "premium website development",
  "modern website development",
  "responsive website development",
  "high performance website development",
  "SEO website development",
  "secure website development",
  "Next.js development company",
  "Next.js development services",
  "React development company",
  "React development services",
  "TypeScript development company",
  "TypeScript development services",
  "frontend development company",
  "frontend development services",
  "backend development company",
  "backend development services",
  "API development company",
  "API development services",
  "REST API development",
  "GraphQL development company",
  "web application development company",
  "web application development services",
  "custom web application development",
  "business web application development",
  "enterprise web application development",
  "SaaS development company",
  "SaaS development services",
  "SaaS application development",
  "SaaS product development",
  "custom SaaS development",
  "MVP development company",
  "MVP development services",
  "startup MVP development",
  "startup software development",
  "startup technology company",
  "startup product development",
  "product development company",
  "product development services",
  "digital product agency",
  "digital product studio",
  "software product studio",

  "mobile app development company",
  "mobile app development agency",
  "mobile application development company",
  "mobile application development services",
  "custom mobile app development",
  "custom mobile application development",
  "Android app development company",
  "Android application development",
  "iOS app development company",
  "iOS application development",
  "cross platform app development",
  "cross platform mobile development",
  "React Native development company",
  "React Native app development",
  "Flutter development company",
  "Flutter app development",
  "mobile software development",
  "mobile product development",
  "business mobile app development",
  "enterprise mobile app development",
  "mobile SaaS development",
  "mobile backend development",
  "mobile API development",
  "mobile UI development",
  "mobile UX development",
  "mobile app consulting",
  "mobile application consulting",
  "mobile app modernization",
  "mobile application modernization",
  "mobile app maintenance",
  "mobile application maintenance",
  "mobile app security",
  "mobile application security",
  "mobile app performance optimization",
  "mobile application performance optimization",
  "mobile app deployment",
  "mobile application deployment",
  "custom Android software",
  "custom iOS software",
  "custom cross platform software",

  "AI development company",
  "AI development services",
  "artificial intelligence development company",
  "artificial intelligence development services",
  "AI software development",
  "AI application development",
  "AI product development",
  "AI integration services",
  "AI consulting company",
  "AI consulting services",
  "generative AI development",
  "generative AI application development",
  "generative AI software development",
  "AI agent development",
  "AI agents development company",
  "AI automation company",
  "AI automation services",
  "business AI solutions",
  "enterprise AI solutions",
  "custom AI solutions",
  "machine learning development company",
  "machine learning services",
  "machine learning software development",
  "intelligent software development",
  "intelligent application development",
  "AI powered applications",
  "AI powered software",
  "AI chatbot development",
  "AI assistant development",
  "custom AI chatbot",
  "custom AI assistant",
  "LLM application development",
  "LLM integration services",
  "large language model development",
  "AI API integration",
  "OpenAI integration services",
  "AI workflow automation",
  "AI business automation",
  "AI data processing",
  "AI recommendation systems",
  "AI search development",
  "semantic search development",
  "RAG application development",
  "retrieval augmented generation development",
  "AI knowledge base development",
  "AI enterprise software",
  "AI SaaS development",
  "AI startup development",
  "AI MVP development",
  "AI product engineering",

  "cloud engineering company",
  "cloud engineering services",
  "cloud software development",
  "cloud application development",
  "cloud consulting company",
  "cloud consulting services",
  "cloud architecture services",
  "cloud infrastructure services",
  "cloud migration services",
  "cloud modernization services",
  "DevOps company",
  "DevOps services",
  "DevOps consulting",
  "DevOps engineering",
  "CI CD implementation",
  "continuous integration services",
  "continuous deployment services",
  "cloud deployment services",
  "production deployment services",
  "application deployment services",
  "Docker development services",
  "containerization services",
  "Kubernetes development services",
  "Kubernetes consulting",
  "serverless development",
  "serverless application development",
  "cloud native development",
  "cloud native software company",
  "cloud native application development",
  "infrastructure automation",
  "deployment automation",
  "hosting architecture",
  "web hosting deployment",
  "Vercel development",
  "Netlify development",
  "Render deployment",
  "cloud application hosting",
  "scalable cloud applications",
  "high availability software",
  "production infrastructure engineering",

  "database development company",
  "database engineering company",
  "database engineering services",
  "database design services",
  "database architecture services",
  "database optimization services",
  "database migration services",
  "database modernization",
  "MongoDB development company",
  "MongoDB development services",
  "MongoDB consulting",
  "MongoDB application development",
  "PostgreSQL development company",
  "PostgreSQL development services",
  "PostgreSQL consulting",
  "PostgreSQL application development",
  "SQL database development",
  "NoSQL development",
  "data architecture services",
  "data engineering services",
  "data management solutions",
  "database security",
  "database performance optimization",
  "database scalability",
  "real time database development",
  "application data architecture",
  "business data systems",
  "enterprise database solutions",
  "custom database software",

  "cybersecurity company",
  "cybersecurity services",
  "application security company",
  "application security services",
  "web application security",
  "mobile application security services",
  "API security services",
  "software security engineering",
  "secure software development",
  "secure application development",
  "security architecture services",
  "cybersecurity consulting",
  "security consulting company",
  "penetration testing services",
  "vulnerability assessment services",
  "security audit services",
  "authentication development",
  "authorization systems",
  "identity management development",
  "access control development",
  "two factor authentication development",
  "MFA implementation",
  "JWT authentication development",
  "secure API development",
  "data protection software",
  "privacy focused software development",
  "enterprise security software",
  "secure cloud applications",
  "DevSecOps services",
  "security engineering company",

  "UI UX design company",
  "UI UX development company",
  "UI UX engineering company",
  "UI UX design services",
  "UX engineering services",
  "product design company",
  "digital product design",
  "web UI design",
  "web UX design",
  "mobile UI design",
  "mobile UX design",
  "dashboard design",
  "admin dashboard design",
  "SaaS UI design",
  "SaaS UX design",
  "enterprise UX design",
  "premium website design",
  "luxury website design",
  "modern interface design",
  "responsive interface design",
  "design system development",
  "component library development",
  "frontend architecture",
  "design engineering",
  "interaction design",
  "motion UI development",
  "accessible web design",
  "accessible application development",
  "WCAG web development",
  "conversion focused website design",

  "ecommerce development company",
  "ecommerce development services",
  "custom ecommerce development",
  "online store development",
  "online shopping platform development",
  "ecommerce website development",
  "ecommerce application development",
  "B2B ecommerce development",
  "B2C ecommerce development",
  "marketplace development company",
  "online marketplace development",
  "payment integration development",
  "payment gateway integration",
  "checkout development",
  "shopping cart development",
  "inventory management software",
  "order management software",
  "customer management software",
  "business management software",
  "CRM development company",
  "CRM software development",
  "ERP software development",
  "business automation software",
  "workflow automation software",
  "booking system development",
  "appointment system development",
  "management dashboard development",
  "business dashboard development",
  "customer portal development",
  "client portal development",

  "API integration company",
  "API integration services",
  "third party API integration",
  "payment API integration",
  "Google API integration",
  "social media API integration",
  "email API integration",
  "SMS API integration",
  "maps API integration",
  "cloud API integration",
  "webhook development",
  "webhook integration",
  "microservices development",
  "microservices architecture",
  "software integration services",
  "system integration company",
  "enterprise integration services",
  "backend architecture",
  "software architecture company",
  "software architecture services",
  "technical architecture consulting",
  "application architecture",
  "scalable software architecture",
  "distributed systems development",
  "real time application development",
  "real time web applications",
  "WebSocket development",
  "Socket.IO development",
  "streaming application development",
  "live streaming software development",

  "Nigeria software development company",
  "Nigeria software engineering company",
  "Nigeria web development company",
  "Nigeria web development agency",
  "Nigeria mobile app development company",
  "Nigeria software company",
  "software company in Nigeria",
  "software developers in Nigeria",
  "full stack developers in Nigeria",
  "web developers in Nigeria",
  "app developers in Nigeria",
  "AI developers in Nigeria",
  "software engineers in Nigeria",
  "technology company in Nigeria",
  "technology consulting in Nigeria",
  "software consulting in Nigeria",
  "digital agency in Nigeria",
  "digital product company Nigeria",
  "custom software Nigeria",
  "custom software development Nigeria",
  "web application development Nigeria",
  "mobile application development Nigeria",
  "SaaS development Nigeria",
  "AI development Nigeria",
  "cybersecurity company Nigeria",
  "cloud engineering Nigeria",
  "DevOps company Nigeria",
  "software development Lagos",
  "software development Abuja",
  "software development Port Harcourt",
  "software development Ibadan",
  "software development Benin City",
  "software development Warri",
  "software development Yenagoa",
  "web development Lagos",
  "web development Abuja",
  "web development Port Harcourt",
  "mobile app development Lagos",
  "mobile app development Abuja",
  "mobile app development Port Harcourt",
  "AI development Lagos",
  "AI development Abuja",
  "AI development Port Harcourt",
  "software engineering Lagos",
  "software engineering Abuja",
  "software engineering Port Harcourt",
  "technology company Lagos",
  "technology company Abuja",
  "technology company Port Harcourt",

  "software development company Africa",
  "software engineering company Africa",
  "web development company Africa",
  "mobile app development Africa",
  "AI development company Africa",
  "technology company Africa",
  "digital product development Africa",
  "custom software development Africa",
  "software consulting Africa",
  "full stack development Africa",
  "software developers Africa",
  "technology solutions Africa",
  "digital transformation Africa",
  "cloud engineering Africa",
  "cybersecurity Africa",
  "SaaS development Africa",
  "software outsourcing Africa",
  "software development outsourcing",
  "nearshore software development",
  "offshore software development",
  "remote software development company",
  "remote software engineering company",
  "global software development company",
  "international software development company",
  "worldwide software development services",
  "software development for startups",
  "software development for businesses",
  "software development for enterprises",
  "software development for organizations",
  "custom software for businesses",
  "custom software for startups",
  "custom software for enterprises",

  "hire full stack developers",
  "hire software developers",
  "hire software engineers",
  "hire web developers",
  "hire mobile developers",
  "hire React developers",
  "hire Next.js developers",
  "hire Node.js developers",
  "hire TypeScript developers",
  "hire React Native developers",
  "hire Flutter developers",
  "hire AI developers",
  "hire cloud engineers",
  "hire DevOps engineers",
  "hire cybersecurity developers",
  "hire backend developers",
  "hire frontend developers",
  "hire database developers",
  "hire software development team",
  "hire development agency",
  "hire software development company",
  "hire technology company",
  "outsource software development",
  "outsource web development",
  "outsource mobile development",
  "outsource app development",
  "outsource SaaS development",
  "outsource AI development",
  "outsource software engineering",
  "software development partner",
  "technology development partner",
  "digital product development partner",

  "best software development company",
  "best software engineering company",
  "best web development company",
  "best mobile app development company",
  "best full stack development company",
  "best software developers",
  "best software development agency",
  "top software development company",
  "top software engineering company",
  "top web development company",
  "top mobile app development company",
  "top full stack development company",
  "leading software development company",
  "leading software engineering company",
  "professional software development company",
  "professional web development company",
  "professional mobile app development company",
  "reliable software development company",
  "reliable software engineering company",
  "premium software development company",
  "premium software engineering company",
  "high quality software development company",
  "custom software experts",
  "software engineering experts",
  "full stack engineering experts",
  "web development experts",
  "mobile app development experts",
  "AI development experts",
  "cloud engineering experts",
  "software architecture experts",
  "digital product experts",

  "software modernization company",
  "application modernization company",
  "legacy software modernization",
  "legacy application modernization",
  "software migration company",
  "application migration services",
  "website redesign company",
  "website modernization services",
  "application redesign services",
  "performance optimization company",
  "web performance optimization",
  "application performance optimization",
  "Core Web Vitals optimization",
  "SEO technical optimization",
  "technical SEO development",
  "website accessibility development",
  "website security development",
  "website maintenance company",
  "software maintenance company",
  "application maintenance services",
  "software support services",
  "technical support software",
  "software quality assurance",
  "software testing services",
  "automated testing services",
  "end to end testing services",
  "API testing services",
  "web application testing",
  "mobile application testing",
  "software reliability engineering",

  "church software development",
  "church website development",
  "church livestream software",
  "livestream platform development",
  "live streaming website development",
  "live video platform development",
  "video streaming software",
  "real time video platform",
  "event streaming platform",
  "event management software",
  "event technology company",
  "media streaming development",
  "broadcast software development",
  "video production software",
  "multi camera streaming software",
  "director streaming dashboard",
  "camera operator streaming platform",
  "online church streaming platform",
  "online event streaming platform",
  "virtual event platform",

  "portfolio website development",
  "corporate software website",
  "engineering company website",
  "technology company website",
  "startup website development",
  "SaaS company website",
  "developer portfolio development",
  "professional company website",
  "premium corporate website",
  "luxury technology website",
  "high end website development",
  "conversion optimized website",
  "lead generation website development",
  "business lead generation software",
  "contact management software",
  "customer lead management",
  "CRM integration",
  "marketing automation development",
  "analytics dashboard development",
  "business analytics software",
  "visitor analytics software",
  "website visitor analytics",
  "customer analytics platform",
  "product analytics development",
  "custom analytics dashboard",

  "software development consultation",
  "software architecture consultation",
  "technology strategy consulting",
  "digital product strategy",
  "technical product strategy",
  "software project planning",
  "technology roadmap consulting",
  "software feasibility study",
  "MVP consulting",
  "startup technology consulting",
  "technical due diligence",
  "software technical audit",
  "application technical audit",
  "website technical audit",
  "SEO technical audit",
  "security technical audit",
  "cloud architecture consulting",
  "database architecture consulting",
  "API architecture consulting",
  "software engineering consulting",

  "TGO DevStudio services",
  "TGO DevStudio portfolio",
  "TGO DevStudio projects",
  "TGO DevStudio blog",
  "TGO DevStudio careers",
  "TGO DevStudio contact",
  "TGO DevStudio services Nigeria",
  "TGO DevStudio web development",
  "TGO DevStudio mobile development",
  "TGO DevStudio AI development",
  "TGO DevStudio SaaS development",
  "TGO DevStudio cloud engineering",
  "TGO DevStudio cybersecurity",
  "TGO DevStudio software consulting",
  "TGO DevStudio digital products",
  "TGO DevStudio custom software",
  "TGO DevStudio software engineering",
  "TGO DevStudio full stack",
  "TGO DevStudio technology consulting",
  "TGO DevStudio digital transformation",
] as const;

export type SeoKeywordTarget =
  (typeof SEO_KEYWORD_TARGETS)[number];
