export const MANAGED_CONTENT_TYPES = [
  { key: "caseStudies", label: "Case Studies" },
  { key: "team", label: "Team" },
  { key: "blogPosts", label: "Blog" },
  { key: "jobOpenings", label: "Careers / Job Openings" },
  { key: "jobApplications", label: "Job Applications" },
  { key: "contactSubmissions", label: "Contact Messages" },
  { key: "reviews", label: "Reviews & Feedback" },
  { key: "services", label: "Services" },
  { key: "processSteps", label: "Process Steps" },
  { key: "pageContent", label: "Site Pages (About/Privacy/Terms)" },
  { key: "homeSettings", label: "Homepage Settings" },
  { key: "availabilityStatus", label: "Availability Status" },
  { key: "bookACallSettings", label: "Book a Call Settings" },
  { key: "stackItems", label: "Stack Items" },
  { key: "helpArticles", label: "Help Articles" },
  { key: "newsletterSubscribers", label: "Newsletter Subscribers" },
  { key: "faqItems", label: "FAQ Items" },
] as const;
