import { NextRequest, NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/db";
import User from "@/models/User";
import Role from "@/models/Role";
import BlogPost from "@/models/BlogPost";
import { slugify } from "@/lib/utils/slugify";

const posts = [
  { title: "What Is a Webhook Secret, With a Real Example", excerpt: "Webhooks need protecting too. Here's how, with a real example.", content: "<p>A webhook secret is a shared password-like value that lets a system verify an incoming webhook actually came from who it claims to.</p><h2>A Real Example</h2><p>When Stripe sends a payment notification to a business's server, it signs that notification using a secret value only Stripe and the business's server know. The server checks this signature before trusting the notification, so a fraudulent message pretending to be from Stripe gets rejected.</p><h2>Why This Matters</h2><p>Without this check, anyone who discovers a webhook's web address could send fake notifications, potentially tricking a system into thinking a payment happened when it didn't.</p><h2>Why This Matters to You</h2><p>Any integration handling money or sensitive actions through webhooks should have this kind of verification in place as standard practice, not an afterthought.</p>", tags: ["Security", "APIs"] },
  { title: "What Is Horizontal vs Vertical Scaling, With a Real Example", excerpt: "There are two real ways to handle more traffic. Here's what each actually means.", content: "<p>Scaling means increasing a system's capacity to handle more load. There are two real approaches.</p><h2>A Real Example: Vertical Scaling</h2><p>Upgrading a single server to a more powerful one — more memory, faster processor — is vertical scaling. It's like replacing one small delivery truck with one much bigger truck.</p><h2>A Real Example: Horizontal Scaling</h2><p>Adding more servers running side by side, sharing the workload, is horizontal scaling. It's like adding more delivery trucks instead of one bigger one.</p><h2>Why the Difference Matters</h2><p>Vertical scaling has a real ceiling — eventually there's no bigger machine available. Horizontal scaling can generally keep growing by adding more machines, which is why most large modern platforms rely on it.</p>", tags: ["Technology", "Performance"] },
  { title: "What Is Zero-Downtime Deployment, With a Real Example", excerpt: "Updates don't have to mean visible downtime. Here's a real explanation.", content: "<p>Zero-downtime deployment means updating a live website with new code without visitors ever seeing an interruption.</p><h2>A Real Example</h2><p>Instead of shutting the whole website down to install an update, a new version is started up alongside the old one, and traffic is smoothly switched over to the new version only once it's confirmed working — visitors never notice a gap.</p><h2>Why This Matters</h2><p>A website that goes fully offline every time it's updated risks losing visitors and looking unreliable, especially if updates happen frequently.</p><h2>Why This Matters to You</h2><p>A hosting setup capable of zero-downtime deployment means your site can be improved constantly without disrupting real customers using it right now.</p>", tags: ["Process", "Technology"] },
  { title: "What Is an Environment Variable, With a Real Example", excerpt: "This is how sensitive settings stay out of a project's actual code. Here's a real example.", content: "<p>An environment variable is a piece of configuration stored outside a project's actual code, often used for sensitive values.</p><h2>A Real Example</h2><p>A website's database password should never be typed directly into its code, especially if that code is ever shared or made public. Instead, it's stored as an environment variable — a value the hosting platform provides separately and securely, which the code reads at runtime without ever displaying the actual password in the code itself.</p><h2>Why This Matters</h2><p>If sensitive passwords were written directly into code, anyone who saw that code would immediately have access to real, working credentials, a serious security risk.</p><h2>Why This Matters to You</h2><p>Proper handling of environment variables is a basic, expected security practice for any professionally built website handling sensitive services.</p>", tags: ["Security", "Beginner Guide"] },
  { title: "What Is Lazy Loading, With a Real Example", excerpt: "This trick makes pages feel faster without cutting content. Here's how.", content: "<p>Lazy loading means only loading content, like images, when they're actually about to be seen, rather than all at once upfront.</p><h2>A Real Example</h2><p>On a long page with fifty images, lazy loading means only the first few images near the top load immediately. As you scroll down, each additional image loads just before it comes into view, rather than the page trying to load all fifty images the instant you arrive.</p><h2>Why This Matters</h2><p>Loading everything upfront, including content far below what you can currently see, wastes time and data unnecessarily, making the page feel slower to start using.</p><h2>Why This Matters to You</h2><p>A website using lazy loading properly tends to feel noticeably faster to visitors, especially on pages with lots of images.</p>", tags: ["Performance", "Beginner Guide"] },
  { title: "What Is a Breaking Change, With a Real Example", excerpt: "This term explains why some software updates require extra care. Here's a real example.", content: "<p>A breaking change is an update that removes or alters something in a way that stops previously working things from continuing to work.</p><h2>A Real Example</h2><p>If an API changes the name of a piece of data it returns, from 'user_name' to 'username,' any other system still expecting the old name will suddenly stop working correctly, even though nothing about their own code changed.</p><h2>Why This Matters</h2><p>Breaking changes can silently damage systems that depend on something, sometimes without immediate obvious warning, until something visibly stops working.</p><h2>How Careful Teams Handle This</h2><p>Clearly documenting breaking changes in advance, and giving other systems time to adjust before the change takes effect, is standard responsible practice.</p>", tags: ["Technology", "Process"] },
  { title: "What Is Idempotency, With a Real Example", excerpt: "This technical word protects against accidental double-charges. Here's a real explanation.", content: "<p>Idempotency means an action can be safely repeated multiple times without causing unintended extra effects beyond the first time.</p><h2>A Real Example</h2><p>Imagine a customer's payment request gets sent, but their internet briefly disconnects before they see confirmation, so they click 'pay' again just in case. A properly built, idempotent payment system recognizes this is the same original request and ensures the customer is only actually charged once, not twice.</p><h2>Why This Matters</h2><p>Without this protection, temporary network hiccups or accidental double-clicks could lead to real customers being charged multiple times for one purchase.</p><h2>Why This Matters to You</h2><p>This is a specific, deliberate engineering consideration that protects both your customers and your business's reputation around payments.</p>", tags: ["Technology", "Security"] },
  { title: "What Is a Content Delivery Failure Fallback, With a Real Example", excerpt: "What happens when part of your site's infrastructure has a hiccup? Here's a real example.", content: "<p>A fallback is a backup response used when a primary system fails to respond as expected.</p><h2>A Real Example</h2><p>If a website normally loads product images from a fast external image service, and that service is temporarily slow or unavailable, a well-built site can fall back to a simple placeholder image instead of showing a completely broken, empty box.</p><h2>Why This Matters</h2><p>Real third-party services occasionally have brief outages or slowdowns beyond your control. A thoughtful fallback keeps your site looking intentional and functional even when something else briefly fails.</p><h2>Why This Matters to You</h2><p>This kind of resilience is a mark of careful engineering, protecting your site's appearance even during external hiccups outside your control.</p>", tags: ["Technology", "Process"] },
  { title: "What Is Input Validation, With a Real Example", excerpt: "This simple practice prevents a surprising amount of real-world problems. Here's how.", content: "<p>Input validation means checking that information entered by a user actually makes sense and is safe, before a system acts on it.</p><h2>A Real Example</h2><p>If a signup form asks for an email address, input validation checks that what was typed actually looks like a real email address — containing an @ symbol, for example — before accepting it, rather than blindly storing whatever was typed, including accidental gibberish or, worse, malicious code disguised as text.</p><h2>Why This Matters</h2><p>Without proper validation, a form becomes an open door for both honest mistakes and deliberate attacks attempting to submit harmful data.</p><h2>Why This Matters to You</h2><p>Every public form on your website — contact, signup, checkout — should have real validation in place as a basic, non-negotiable requirement.</p>", tags: ["Security", "Beginner Guide"] },
  { title: "What Is Output Encoding, With a Real Example", excerpt: "This quietly prevents a common and serious website attack. Here's a real explanation.", content: "<p>Output encoding means safely converting user-submitted content before displaying it back on a page, so it can't be misused to run harmful code.</p><h2>A Real Example</h2><p>If someone submits a comment containing actual programming code disguised as a comment, proper output encoding ensures that code is displayed as harmless plain text on the page, rather than accidentally being run as if it were real functioning code, which could let an attacker hijack other visitors' browsers.</p><h2>Why This Matters</h2><p>This specific type of attack, called cross-site scripting, is one of the most common real vulnerabilities found on poorly built websites.</p><h2>Why This Matters to You</h2><p>Any site that displays user-submitted content — reviews, comments, forum posts — needs this protection properly in place as standard, expected practice.</p>", tags: ["Security", "Technology"] },
  { title: "What Is Database Indexing, With a Real Example", excerpt: "This is why some searches on big sites are instant. Here's a real explanation.", content: "<p>A database index is a structure that helps a database find specific information much faster, similar to an index at the back of a book.</p><h2>A Real Example</h2><p>Searching for a specific customer by email in a database with a million records, without an index, might mean checking every single record one by one. With a proper index built specifically on the email field, the database can jump almost directly to the right record, dramatically faster.</p><h2>Why This Matters</h2><p>As a business's data grows, searches that were once instant can become noticeably slow without proper indexing in place.</p><h2>Why This Matters to You</h2><p>A database designed thoughtfully from the start, with proper indexing on frequently searched fields, keeps your platform fast even as your real data grows.</p>", tags: ["Databases", "Performance"] },
  { title: "What Is a Soft Delete, With a Real Example", excerpt: "Sometimes 'deleting' something doesn't actually erase it. Here's a real, useful example.", content: "<p>A soft delete marks something as removed without actually permanently erasing the underlying data.</p><h2>A Real Example</h2><p>When an admin 'deletes' a customer's account on some platforms, the account might just be marked as deleted and hidden from normal view, rather than instantly and permanently wiped. This means if the deletion was a mistake, or if the business is later legally required to retrieve past records, the real data can still be recovered.</p><h2>Why This Matters</h2><p>Permanent, immediate deletion offers no recovery path if something goes wrong. A soft delete offers a safer middle ground for many types of important data.</p><h2>The Trade-Off to Understand</h2><p>Soft-deleted data still needs proper handling to respect genuine privacy deletion requests when legally required, not kept indefinitely without limit.</p>", tags: ["Databases", "Process"] },
  { title: "What Is a Content Security Policy (CSP), With a Real Example", excerpt: "This is a real security layer many sites quietly rely on. Here's how it works.", content: "<p>A Content Security Policy is a set of rules a website tells the browser to follow, restricting what sources of content are allowed to run on that page.</p><h2>A Real Example</h2><p>A website's CSP might explicitly state that scripts are only allowed to load from its own domain and a couple of specifically trusted, named services, nothing else. If an attacker somehow manages to inject a malicious script from an unauthorized source, the browser itself will refuse to run it, because it violates the site's declared policy.</p><h2>Why This Matters</h2><p>This acts as a real, meaningful extra layer of defense, even if another part of a site's security has a weakness elsewhere.</p><h2>Why This Matters to You</h2><p>A properly configured CSP is considered a genuine security best practice for any modern, professionally built website.</p>", tags: ["Security", "Technology"] },
  { title: "What Is Multi-Tenancy, With a Real Example", excerpt: "This concept lets one platform serve many separate customers securely. Here's a real example.", content: "<p>Multi-tenancy means one single system serves multiple separate customers or organizations, while keeping each one's data properly isolated from the others.</p><h2>A Real Example</h2><p>A project-management platform like TGO Flow might host hundreds of different companies on the same underlying system, but each company can only ever see and access their own team's projects and data, never another company's, even though they're technically running on shared, common infrastructure.</p><h2>Why This Matters</h2><p>Building this correctly is genuinely more complex than building separate, isolated systems for each customer, but it's far more cost-efficient to operate and maintain at scale.</p><h2>Why This Matters to You</h2><p>If you're evaluating a shared software platform, understanding that proper multi-tenancy protects your data from other customers on the same system is a fair, important question to ask about.</p>", tags: ["Technology", "Security"] },
  { title: "What Is a Feature Flag, With a Real Example", excerpt: "This lets teams release features safely and gradually. Here's a real explanation.", content: "<p>A feature flag is a switch in code that lets a specific feature be turned on or off, or shown to only some users, without needing a whole new deployment.</p><h2>A Real Example</h2><p>A business wanting to test a new checkout design might turn it on for just 10% of real visitors first, using a feature flag, watching closely for any problems, before confidently rolling it out to everyone once it's proven stable.</p><h2>Why This Matters</h2><p>This lets teams catch problems with a new feature while it's only affecting a small portion of real users, rather than everyone at once.</p><h2>Why This Matters to You</h2><p>This is a genuinely safer, more controlled way to introduce meaningful changes to a live product that real customers depend on.</p>", tags: ["Process", "Technology"] },
  { title: "What Is Dependency Management, With a Real Example", excerpt: "Modern software relies on many outside pieces. Here's what managing them really means.", content: "<p>A dependency is an external piece of code a project relies on to work. Dependency management means keeping track of and maintaining all of these properly.</p><h2>A Real Example</h2><p>This very website relies on dozens of external code packages — for things like handling images, sending emails, and rendering pages — each maintained by other developers elsewhere. Proper dependency management means keeping these updated, and being aware if any of them develops a known security problem.</p><h2>Why This Matters</h2><p>An outdated dependency with a known security weakness can become a real, exploitable entry point into an otherwise well-built website, if left unaddressed.</p><h2>Why This Matters to You</h2><p>Ask any development partner how they handle keeping dependencies updated and monitored — it's a legitimate, meaningful question about ongoing security.</p>", tags: ["Security", "Maintenance"] },
  { title: "What Is a Health Check Endpoint, With a Real Example", excerpt: "This small feature helps systems know if they're actually working. Here's a real example.", content: "<p>A health check endpoint is a small, dedicated part of a system specifically built to answer the question 'are you working correctly right now?'</p><h2>A Real Example</h2><p>A monitoring tool might regularly visit a specific address like yoursite.com/health, expecting a simple 'yes, I'm fine' response. If the site fails to respond properly, the monitoring tool knows immediately something is wrong, even before a real human visitor might notice or report it.</p><h2>Why This Matters</h2><p>This gives automated systems a clear, reliable, lightweight way to check on a website's real status, without needing to load an entire complex page just to find out.</p><h2>Why This Matters to You</h2><p>This is one small but meaningful piece of a properly monitored, professionally maintained website.</p>", tags: ["Technology", "Maintenance"] },
  { title: "What Is Data Normalization, With a Real Example", excerpt: "This database concept prevents messy, duplicated information. Here's a real example.", content: "<p>Data normalization means organizing a database so that each piece of information is stored in exactly one proper place, avoiding unnecessary duplication.</p><h2>A Real Example</h2><p>Instead of storing a customer's full address repeatedly inside every single one of their orders, a normalized database stores that customer's address once, in one dedicated customer record, and each order simply references back to that one customer. If the customer updates their address, it only needs updating in one single place.</p><h2>Why This Matters</h2><p>Without proper normalization, updating one piece of information might require finding and changing it in many different scattered places, risking some being missed and becoming inconsistent.</p><h2>Why This Matters to You</h2><p>A properly structured database stays more accurate and reliable as your real business data grows over time.</p>", tags: ["Databases", "Technology"] },
  { title: "What Is Cross-Origin Resource Sharing (CORS), With a Real Example", excerpt: "This explains a common, confusing browser error. Here's what it actually means.", content: "<p>CORS is a browser security rule that controls whether one website is allowed to request data from a different website.</p><h2>A Real Example</h2><p>If yourbusiness.com tries to directly request data from a completely unrelated website's private API, without that other website explicitly allowing it, the browser blocks the request for security reasons, showing what's known as a CORS error. This exists to prevent unrelated websites from freely pulling data from services that haven't agreed to share it.</p><h2>Why This Matters</h2><p>Without this rule, malicious websites could more easily and silently pull private data from other services a visitor happened to be logged into elsewhere.</p><h2>Why This Matters to You</h2><p>If your website needs to properly connect to another service's API, that other service needs to explicitly allow your site through CORS settings, a normal and expected part of legitimate integrations.</p>", tags: ["Security", "APIs"] },
  { title: "What Is Server Logging, With a Real Example", excerpt: "This is how problems get diagnosed after the fact. Here's a real, practical example.", content: "<p>Server logging means a system automatically recording notes about what's happening as it runs, creating a detailed history to look back on.</p><h2>A Real Example</h2><p>If a customer reports that an order mysteriously failed, a development team can look through the server's logs from that exact time, finding a detailed, timestamped record of exactly what happened during that failed request, helping them understand and fix the real underlying cause.</p><h2>Why This Matters</h2><p>Without proper logging, diagnosing a problem after it happens becomes largely guesswork, since there's no real record of what actually occurred.</p><h2>Why This Matters to You</h2><p>A professionally built system logs meaningful events properly, which directly speeds up how quickly real problems can be found and fixed when they occur.</p>", tags: ["Technology", "Maintenance"] },
  { title: "What Is a Circuit Breaker Pattern, With a Real Example", excerpt: "This protects systems from cascading failures. Here's a real, understandable example.", content: "<p>A circuit breaker pattern means a system automatically stops trying to use another service that's clearly failing, rather than repeatedly hammering it and making things worse.</p><h2>A Real Example</h2><p>If a website relies on an external email service that suddenly starts failing constantly, a circuit breaker pattern means the website temporarily stops sending requests to that failing service altogether for a short period, instead of continuing to try repeatedly and potentially slowing down the entire website while waiting on a service that clearly isn't responding.</p><h2>Why This Matters</h2><p>Without this protection, one failing external service can sometimes drag down the performance of an otherwise healthy website trying repeatedly to reach it.</p><h2>Why This Matters to You</h2><p>This kind of resilience thinking protects your website's overall stability even when a service it depends on has problems.</p>", tags: ["Technology", "Process"] },
  { title: "What Is Accessibility Testing, With a Real Example", excerpt: "This goes beyond just having good intentions about accessibility. Here's a real example.", content: "<p>Accessibility testing means actually checking whether a website genuinely works for people with disabilities, rather than just assuming it does.</p><h2>A Real Example</h2><p>A developer might use an actual screen reader tool — the kind visually impaired users rely on — to navigate through their own website, discovering firsthand that an important button has no readable label, making it invisible to that screen reader, even though it looks perfectly fine visually.</p><h2>Why This Matters</h2><p>Good intentions alone don't guarantee real accessibility. Only actual testing with real assistive tools reliably catches these kinds of genuine, practical gaps.</p><h2>Why This Matters to You</h2><p>This kind of real testing is what separates a website that claims to be accessible from one that genuinely, practically is.</p>", tags: ["Accessibility", "Process"] },
  { title: "What Is API Versioning, With a Real Example", excerpt: "This lets systems evolve without breaking everyone using them. Here's a real example.", content: "<p>API versioning means offering different numbered versions of an API, so changes can be introduced without immediately breaking everyone currently using an older version.</p><h2>A Real Example</h2><p>A payment provider might keep an older 'version 1' of their API running exactly as-is for existing businesses relying on it, while offering a new 'version 2' with improvements for anyone ready to switch, rather than forcing every single user to update immediately the moment anything changes.</p><h2>Why This Matters</h2><p>This gives real businesses relying on an API the time and stability they need to adjust to changes on their own schedule, rather than being forced into sudden, disruptive updates.</p><h2>Why This Matters to You</h2><p>If your business integrates with another company's API, understanding their versioning approach tells you how much stability and advance warning you can realistically expect from them.</p>", tags: ["APIs", "Business Advice"] },
  { title: "What Is a Postmortem, With a Real Example", excerpt: "This is how serious teams learn from real failures. Here's a real, honest example.", content: "<p>A postmortem is a structured, honest review conducted after something goes wrong, aimed at understanding what happened and preventing it from happening again.</p><h2>A Real Example</h2><p>After a website experiences unexpected downtime, a responsible team doesn't just fix the immediate problem and move on. They write up exactly what happened, why it happened, how it was fixed, and what specific changes will prevent this same exact problem from happening again in the future.</p><h2>Why This Matters</h2><p>Without this honest reflection, the same type of problem can easily repeat itself later, since the real underlying cause was never properly addressed.</p><h2>Why This Matters to You</h2><p>A development partner willing to conduct honest postmortems after real problems is one genuinely focused on long-term reliability, not just quick, surface-level fixes.</p>", tags: ["Process", "Business Advice"] },
];

export async function GET(request: NextRequest) {
  const providedSecret = request.headers.get("x-cron-secret");
  const expectedSecret = process.env.CRON_SECRET;
  if (!expectedSecret || providedSecret !== expectedSecret) {
    return NextResponse.json({ status: "error", message: "Unauthorized." }, { status: 401 });
  }

  await connectToDatabase();

  const founderRole = await Role.findOne({ isFounderRole: true });
  const founder = founderRole ? await User.findOne({ role: founderRole._id }) : null;
  if (!founder) {
    return NextResponse.json({ status: "error", message: "No founder account found." }, { status: 500 });
  }

  let created = 0;
  let skipped = 0;

  for (const post of posts) {
    const slug = slugify(post.title);
    const existing = await BlogPost.findOne({ slug });
    if (existing) {
      skipped++;
      continue;
    }
    await BlogPost.create({
      title: post.title,
      slug,
      excerpt: post.excerpt,
      contentHtml: post.content,
      tags: post.tags,
      publishStatus: "published",
      featured: false,
      createdBy: founder._id,
    });
    created++;
  }

  return NextResponse.json({ status: "ok", created, skipped });
}
