import { NextRequest, NextResponse } from "next/server";
import { connectToDatabase } from "@/lib/db";
import User from "@/models/User";
import Role from "@/models/Role";
import BlogPost from "@/models/BlogPost";
import { slugify } from "@/lib/utils/slugify";

const posts = [
  { title: "What Is a Framework, With a Real Example", excerpt: "Developers mention frameworks constantly. Here's a real, concrete explanation.", content: "<p>A framework is a pre-built foundation of code that developers build on top of, instead of starting completely from scratch.</p><h2>A Real Example</h2><p>This very site, TGO DevStudio Prime, is built using a framework called Next.js. Instead of writing raw low-level code to handle every single webpage request from zero, Next.js already provides ready-made, tested solutions for things like page routing and performance, so developers can focus on the actual unique features of the site.</p><h2>Why Not Build Everything From Scratch?</h2><p>Building every basic piece from zero for every project would be slow, repetitive, and far more likely to contain mistakes than using a framework that thousands of other developers have already tested and improved over time.</p><h2>Why This Matters to You</h2><p>The framework a team chooses affects your project's speed, security, and how easy it is for other developers to maintain later. A reputable, well-supported framework is a real advantage, not just a technical preference.</p>", tags: ["Technology", "Beginner Guide"] },
  { title: "What Is JSON, With a Real Example", excerpt: "This format quietly powers most of the internet's data exchange. Here's what it actually looks like.", content: "<p>JSON is a simple, structured way of writing data so that both humans and computers can read it easily.</p><h2>A Real Example</h2><p>When an app asks a weather API for today's forecast, the API might respond with something like: city name, temperature, and condition, all clearly labeled and organized. This structured response is written in JSON format specifically because it's simple, lightweight, and understood by virtually every programming language.</p><h2>Why This Matters</h2><p>JSON is the common language that lets different systems, built by different companies using different tools, exchange information smoothly. It's part of why the modern internet's many separate services can work together at all.</p><h2>Where You Might Actually See It</h2><p>If you've ever exported settings from an app, or looked at a website's technical data in a browser's developer tools, you've likely seen JSON directly, even without realizing its name.</p>", tags: ["Technology", "APIs"] },
  { title: "What Is Caching, With a Real Example", excerpt: "Caching is one of the simplest ways to make a website feel faster. Here's how it really works.", content: "<p>Caching means temporarily storing a copy of something so it can be delivered again quickly, without redoing the original work each time.</p><h2>A Real Example</h2><p>Imagine a restaurant that gets asked for its menu hundreds of times a day. Instead of handwriting a fresh menu from scratch for every single customer, they print copies in advance and hand them out instantly. A website does something similar: instead of rebuilding a webpage from scratch for every single visitor, it can store a ready copy and serve that same copy quickly to many visitors, only rebuilding it occasionally.</p><h2>Why This Matters</h2><p>Caching can dramatically reduce how long a page takes to load, and reduce the load on the server itself, since it isn't repeating the same work unnecessarily.</p><h2>The Trade-Off to Understand</h2><p>Cached content can occasionally be slightly outdated if it isn't refreshed often enough. Good engineering means deciding carefully how long something can safely stay cached before it needs updating.</p>", tags: ["Performance", "Technology"] },
  { title: "What Is a Cookie, With a Real Example", excerpt: "Not the edible kind. Here's what website cookies actually do, explained simply.", content: "<p>A cookie, in web terms, is a small piece of information a website stores in your browser to remember something about you.</p><h2>A Real Example</h2><p>When you dismiss a cookie-consent banner on a website, and it doesn't reappear the next time you visit that same site, that's a cookie at work — the website stored a small note in your browser saying 'this visitor already responded,' so it remembers not to ask again.</p><h2>What Else Cookies Are Used For</h2><p>Keeping you logged into a website between visits, remembering items in a shopping cart, and remembering site preferences like language settings are all commonly handled through cookies.</p><h2>Why This Became a Big Privacy Topic</h2><p>Some cookies are also used to track browsing behavior across different websites for advertising purposes, which is why privacy regulations now require websites to disclose and get consent for their cookie usage.</p>", tags: ["Beginner Guide", "Legal"] },
  { title: "What Is Encryption, With a Real Example", excerpt: "Encryption protects data constantly without most people noticing. Here's a real, understandable example.", content: "<p>Encryption is the process of scrambling information so that only someone with the correct key can turn it back into readable form.</p><h2>A Real Example</h2><p>When you send a message through WhatsApp, that message is encrypted before it leaves your phone. Even WhatsApp itself cannot read the actual content of that message as it travels — only your phone and the recipient's phone hold the keys needed to unscramble it back into readable text.</p><h2>Why This Matters</h2><p>Without encryption, sensitive information like passwords, messages, or payment details could be read by anyone who intercepts them while traveling across the internet.</p><h2>Two Common Places You Rely on Encryption</h2><p>The HTTPS padlock on websites, and password storage systems that scramble your password so that even the company storing it cannot see your actual original password, both rely on encryption.</p>", tags: ["Security", "Beginner Guide"] },
  { title: "What Is a Firewall, With a Real Example", excerpt: "Firewalls are a basic layer of digital security. Here's a clear, real-world explanation.", content: "<p>A firewall is a security system that monitors and controls what kind of traffic is allowed in or out of a network or server.</p><h2>A Real Example</h2><p>Think of a security guard at a building's entrance, checking everyone's ID before letting them in, and turning away anyone without proper credentials. A firewall does something similar for a server — it checks incoming connection attempts and blocks ones that look suspicious or unauthorized, while allowing legitimate traffic through.</p><h2>Why This Matters</h2><p>Without a firewall, a server is exposed to essentially anyone on the internet attempting to connect to it directly, including people with malicious intent.</p><h2>Where This Applies to Your Business</h2><p>Even a small business website benefits from proper firewall configuration as part of a broader, layered security approach, not as a single complete solution on its own.</p>", tags: ["Security", "Beginner Guide"] },
  { title: "What Is Latency, With a Real Example", excerpt: "This word explains why some websites feel instant and others feel sluggish. Here's what it means.", content: "<p>Latency is the delay between when a request is sent and when a response is received.</p><h2>A Real Example</h2><p>If you click a link and the page takes half a second to start loading, that half-second gap before anything happens is latency. Some of that delay comes from the physical distance data has to travel, and some comes from how efficiently the server processes the request.</p><h2>Why Distance Genuinely Matters</h2><p>A server in Europe responding to a visitor in Europe will typically have lower latency than that same server responding to a visitor in another part of the world, purely because of the physical distance the data has to travel, even at close to the speed of light.</p><h2>Why This Matters for Your Business</h2><p>If your customers are mostly local, hosting your website in or near that same region can meaningfully reduce latency and make your site feel snappier.</p>", tags: ["Performance", "Technology"] },
  { title: "What Is Uptime Monitoring, With a Real Example", excerpt: "You want to know your website is down before your customers tell you. Here's how that actually works.", content: "<p>Uptime monitoring is an automated system that regularly checks whether your website is actually online and working.</p><h2>A Real Example</h2><p>An automated tool visits your website every few minutes, checking if it loads properly. If your site suddenly stops responding, the monitoring tool immediately sends you an alert — often within minutes — so you can start fixing the problem right away, ideally before many customers even notice.</p><h2>Why This Matters</h2><p>Without monitoring, a business might not find out their website is down until a customer complains, by which point they may have already lost sales or trust.</p><h2>What Good Monitoring Looks Like</h2><p>Real monitoring checks not just whether a site loads, but also whether it's loading correctly and within a reasonable time, catching problems that a simple glance wouldn't reveal.</p>", tags: ["Maintenance", "Business Advice"] },
  { title: "What Is a Sitemap, With a Real Example", excerpt: "This quiet file helps search engines find your content. Here's what it actually does.", content: "<p>A sitemap is a structured list of every important page on your website, meant to help search engines understand your site's full structure.</p><h2>A Real Example</h2><p>Imagine handing a new visitor a table of contents for your entire website before they even start browsing, listing your homepage, about page, every blog post, and every service page. A sitemap does exactly this, but for search engines like Google instead of human visitors, helping them discover and properly index all your content.</p><h2>Why This Matters</h2><p>Without a sitemap, a search engine might take longer to discover some of your pages, or might miss some entirely, especially on a large site.</p><h2>Where This Site's Sitemap Lives</h2><p>Most modern websites, including this one, automatically generate and update their sitemap, so newly published pages get properly signaled to search engines without manual effort.</p>", tags: ["SEO", "Beginner Guide"] },
  { title: "What Is Structured Data (Schema.org), With a Real Example", excerpt: "This is why some search results show extra details like ratings or prices. Here's how.", content: "<p>Structured data is extra, hidden labeling added to a webpage that explicitly tells search engines what different pieces of content actually mean.</p><h2>A Real Example</h2><p>When you search for a recipe online and see a search result showing a star rating and cooking time directly in the search results, before you even click the link, that's structured data at work. The webpage explicitly labeled its content as 'this is a recipe, this number is the rating, this number is the cooking time,' letting Google display it richly.</p><h2>Why This Matters</h2><p>Structured data can make your website's search listing stand out with extra useful details, potentially increasing how many people click through to your site instead of a competitor's.</p><h2>Where This Applies</h2><p>Businesses, products, reviews, and articles are common types of content that benefit from structured data, helping search engines represent them more richly and accurately.</p>", tags: ["SEO", "Technology"] },
  { title: "What Is a Progressive Web App (PWA), With a Real Example", excerpt: "You may have already installed one without realizing it. Here's a real explanation.", content: "<p>A Progressive Web App is a website built to behave like an installable app, without requiring a traditional app-store download.</p><h2>A Real Example</h2><p>This very site, TGO DevStudio Prime, is a PWA — visiting it in a mobile browser gives you the option to install it directly to your home screen, where it opens in its own window without the browser's address bar, just like a regular app would.</p><h2>Why This Approach Exists</h2><p>Building and maintaining a separate native app for iOS and Android, on top of a website, is expensive and time-consuming. A PWA lets a business offer an app-like experience using the same website codebase, at a fraction of the cost.</p><h2>The Honest Trade-Off</h2><p>PWAs can't access every single feature a fully native app can, but for most business websites, the gap is small enough that the cost savings are well worth it.</p>", tags: ["Technology", "Business Advice"] },
  { title: "What Is Rate Limiting, With a Real Example", excerpt: "This quietly protects websites from abuse every day. Here's a clear example of how.", content: "<p>Rate limiting restricts how many times someone can perform a specific action within a certain period of time.</p><h2>A Real Example</h2><p>Imagine a login page that allows unlimited password attempts. Someone could write a program to guess millions of password combinations rapidly until one works. With rate limiting in place, after a handful of failed attempts in a short time, the system temporarily blocks further attempts from that source, making this kind of attack impractical.</p><h2>Where Else This Applies</h2><p>Contact forms, comment sections, and account creation pages commonly use rate limiting to prevent spam and abuse from automated bots submitting content repeatedly and rapidly.</p><h2>Why This Matters to You</h2><p>A website without rate limiting on sensitive actions like login and form submissions is genuinely more vulnerable to automated attacks and spam than one that has it properly configured.</p>", tags: ["Security", "Technology"] },
  { title: "What Is Responsive Testing, With a Real Example", excerpt: "Designing for mobile isn't enough — it has to actually be tested. Here's why, and how.", content: "<p>Responsive testing means actually checking how a website looks and behaves across many different real screen sizes and devices, not just assuming it works.</p><h2>A Real Example</h2><p>A developer might build a page that looks perfect on their own large desktop monitor, but when actually tested on a small older phone screen, a button might overlap with text, or an image might not resize properly. Responsive testing catches this kind of real, visible problem before real visitors encounter it.</p><h2>Why Assuming Isn't Enough</h2><p>There are enormous differences between phone models, screen sizes, and browsers. Code that 'should' work on all of them in theory sometimes genuinely doesn't in practice, which is exactly why real testing matters.</p><h2>What This Looks Like Done Properly</h2><p>A careful team checks a site across multiple real device sizes — small phones, tablets, and desktops — before considering a page finished.</p>", tags: ["Process", "Design"] },
  { title: "What Is a Regression Bug, With a Real Example", excerpt: "This is why testing after every update matters. Here's a real, relatable example.", content: "<p>A regression bug is a problem that appears in something that used to work correctly, caused by an unrelated later change.</p><h2>A Real Example</h2><p>Imagine a checkout page that works perfectly. A developer later updates the site's navigation menu, unrelated to checkout. But because of how the code was connected, that navigation update accidentally breaks the checkout button. The checkout wasn't touched directly, yet it broke anyway — that's a regression bug.</p><h2>Why This Happens Even to Careful Teams</h2><p>Modern websites have many interconnected parts. A change in one area can sometimes have unexpected ripple effects elsewhere, especially in complex systems.</p><h2>Why Automated Testing Matters Here</h2><p>Automated tests that check core features like checkout after every single change can catch this kind of regression immediately, before it ever reaches real customers.</p>", tags: ["Process", "Technology"] },
  { title: "What Is a Staging Environment, With a Real Example", excerpt: "This is how serious teams avoid testing directly on a live, real website. Here's why it matters.", content: "<p>A staging environment is a private, non-public copy of a website used for testing changes before they go live to real visitors.</p><h2>A Real Example</h2><p>Before updating the pricing on a real, live online store, a careful team first makes that change on a staging copy of the site — one that looks and works identically, but isn't visible to real customers. They check everything works correctly there first, then apply the same change to the real live site.</p><h2>Why This Matters</h2><p>Testing changes directly on a live website risks real customers seeing broken pages, incorrect prices, or errors while a problem is being fixed in real time.</p><h2>The Trade-Off to Understand</h2><p>Maintaining a staging environment takes some extra setup and discipline, but for any business genuinely relying on its website, this precaution is well worth the investment.</p>", tags: ["Process", "Business Advice"] },
  { title: "What Is Code Refactoring, With a Real Example", excerpt: "This isn't adding new features — it's real, valuable maintenance work. Here's a clear example.", content: "<p>Refactoring means improving the internal structure of existing code without changing what it actually does from the outside.</p><h2>A Real Example</h2><p>Imagine a messy kitchen where a chef can still cook meals, but ingredients are scattered everywhere and hard to find quickly. Refactoring is like reorganizing that kitchen properly — nothing about the final meal changes, but everything becomes easier, faster, and safer to work with going forward.</p><h2>Why This Isn't Wasted Time</h2><p>Poorly organized code becomes progressively harder and riskier to add new features to over time. Regular refactoring keeps a codebase healthy and genuinely speeds up future development.</p><h2>Why This Matters to You as a Client</h2><p>A development partner who occasionally recommends refactoring time isn't being inefficient — they're protecting your project's long-term health and your future costs.</p>", tags: ["Process", "Technology"] },
  { title: "What Is a Single Point of Failure, With a Real Example", excerpt: "This concept explains why redundancy matters in serious systems. Here's a real example.", content: "<p>A single point of failure is one specific part of a system that, if it breaks, brings down the entire system with it.</p><h2>A Real Example</h2><p>Imagine a business that relies on exactly one employee who is the only person who knows how to process orders. If that one person is unavailable, the entire order process stops completely. In technology terms, if a website relies on exactly one server with no backup, and that one server fails, the whole website goes down.</p><h2>Why This Matters</h2><p>Identifying and removing single points of failure — through backups, redundant systems, or documented processes — makes a business or system genuinely more resilient to real, inevitable problems.</p><h2>A Realistic Approach</h2><p>Not every single point of failure needs eliminating immediately; the goal is understanding which ones would actually cause the most damage, and addressing those first.</p>", tags: ["Business Advice", "Technology"] },
  { title: "What Is Continuous Integration (CI), With a Real Example", excerpt: "This is how modern teams catch problems automatically before they reach users. Here's how.", content: "<p>Continuous Integration is an automated process that checks a project's code every time a change is made, before that change is allowed to move forward.</p><h2>A Real Example</h2><p>Whenever a developer working on TGO DevStudio Prime pushes a code change, an automated system immediately builds the project and runs checks, catching problems like broken code right away, often within minutes, rather than someone discovering it days later by accident.</p><h2>Why This Matters</h2><p>Without this kind of automated check, mistakes can slip through unnoticed until they cause real, visible problems on the live website.</p><h2>The Real Benefit for a Business Owner</h2><p>A team using continuous integration is catching many mistakes automatically and early, which generally means fewer surprises and a more stable, reliable product for you.</p>", tags: ["Process", "Technology"] },
  { title: "What Is a Race Condition, With a Real Example", excerpt: "This tricky bug type causes real, strange problems in real systems. Here's a clear example.", content: "<p>A race condition happens when two things try to happen at almost exactly the same time, and the unpredictable order they actually complete in causes an incorrect result.</p><h2>A Real Example</h2><p>Imagine an online store has exactly one item left in stock. Two different customers click 'buy' at nearly the same instant. Without careful handling, both purchases might succeed, even though there was only one item available — because both requests were processed at nearly the same time, before the system had properly updated the stock count for either one.</p><h2>Why This Is Tricky to Catch</h2><p>Race conditions often don't show up in normal, slow-paced testing — they tend to appear only under real, simultaneous, high-traffic conditions, making them genuinely difficult bugs to catch in advance.</p><h2>Why This Matters</h2><p>Careful, experienced developers specifically design systems handling things like inventory or payments to properly account for this exact scenario.</p>", tags: ["Technology", "Process"] },
  { title: "What Is Data Redundancy (Backups Explained Deeper), With a Real Example", excerpt: "One backup usually isn't enough. Here's a real example of why redundancy matters.", content: "<p>Data redundancy means keeping more than one copy of important information, stored in genuinely separate places.</p><h2>A Real Example</h2><p>A business keeping their only backup on the same physical server as their live website has a real problem: if that entire server fails or is compromised, both the live site and its backup are lost together. Proper redundancy means storing a backup copy somewhere genuinely separate — a different server, a different provider, or a different physical location entirely.</p><h2>Why 'One Backup' Isn't True Safety</h2><p>A backup only truly protects you if it can survive whatever might happen to the original. A backup stored right next to the original doesn't protect against many real, common failure scenarios.</p><h2>What Good Backup Practice Looks Like</h2><p>Multiple copies, stored separately, taken regularly, and occasionally actually tested to confirm they can be restored successfully.</p>", tags: ["Security", "Business Advice"] },
  { title: "What Is Vendor Lock-In, With a Real Example", excerpt: "This affects your long-term flexibility more than most people realize. Here's a real explanation.", content: "<p>Vendor lock-in happens when a business becomes so dependent on one specific provider's tools that switching away later becomes very difficult or costly.</p><h2>A Real Example</h2><p>Imagine a business builds its entire website using a specific platform's proprietary, closed system that only works on that platform. Years later, if that provider raises prices dramatically or shuts down, the business may struggle to move their website elsewhere, since it was built in a way that only works within that one specific system.</p><h2>Why This Matters</h2><p>Choosing tools and technologies with broader industry support, and genuinely owning your own code and data, gives a business real flexibility and negotiating power in the future.</p><h2>A Balanced View</h2><p>Some level of dependency on chosen tools is normal and fine; the real question is whether you could reasonably move away if you ever truly needed to.</p>", tags: ["Business Advice", "Technology"] },
  { title: "What Is Semantic HTML, With a Real Example", excerpt: "This quiet coding practice affects accessibility and SEO more than people realize. Here's why.", content: "<p>Semantic HTML means using code elements that accurately describe the actual meaning of the content, not just its visual appearance.</p><h2>A Real Example</h2><p>A page's main heading can be written in a way that's properly marked as 'this is the main heading,' or it could be written in a way that just visually looks big and bold without actually being marked as a heading at all. Both might look identical to a sighted visitor, but a screen reader used by a visually impaired visitor, and search engines, can only properly understand the first, correctly marked version.</p><h2>Why This Matters for Real People</h2><p>Visitors using screen readers rely on this proper structure to navigate a page meaningfully, rather than experiencing it as one confusing wall of text.</p><h2>Why This Also Matters for Search Engines</h2><p>Search engines use this same proper structure to understand what a page is actually about, which can genuinely affect how well your site ranks.</p>", tags: ["Beginner Guide", "SEO"] },
  { title: "What Is a Design System, With a Real Example", excerpt: "This keeps large products looking consistent as they grow. Here's a real explanation.", content: "<p>A design system is a defined, reusable set of visual rules and components — colors, buttons, spacing, typography — that a team consistently reuses throughout a product.</p><h2>A Real Example</h2><p>Instead of every new page on a website having a slightly different-looking button, a design system defines exactly one 'primary button' style, used consistently everywhere across the entire site. When it needs updating, changing it in one place updates it everywhere it's used.</p><h2>Why This Matters</h2><p>Without a design system, a growing website often starts looking inconsistent and unprofessional over time, as different pages built at different times drift apart visually.</p><h2>Why This Matters to You</h2><p>A business with a proper design system can add new pages and features faster, while keeping everything looking cohesively branded and professional.</p>", tags: ["Design", "Process"] },
  { title: "What Is Server Uptime SLA, With a Real Example", excerpt: "Hosting providers advertise numbers like '99.9% uptime.' Here's what that promise actually means.", content: "<p>An SLA, or Service Level Agreement, is a formal promise from a provider about the reliability of their service, often expressed as an uptime percentage.</p><h2>A Real Example</h2><p>A hosting provider promising '99.9% uptime' is essentially promising your website will be down for no more than roughly 8-9 hours total across an entire year. A provider promising '99.99%' is promising far less downtime, closer to under an hour a year.</p><h2>Why the Small Differences Actually Matter</h2><p>Those decimal points represent meaningfully different real-world amounts of potential downtime for your business over a year, even though the percentages look nearly identical at first glance.</p><h2>Why This Matters to You</h2><p>Understanding what an SLA actually promises helps you make a fully informed choice between hosting providers, rather than assuming all uptime promises are equivalent.</p>", tags: ["Business Advice", "Technology"] },
  { title: "What Is a Sandbox Environment, With a Real Example", excerpt: "This lets developers test risky things safely. Here's a clear, real example.", content: "<p>A sandbox is an isolated testing space where actions can be tried safely, without any real, permanent consequences.</p><h2>A Real Example</h2><p>Payment providers like Stripe offer a 'sandbox mode' where developers can test an entire checkout process using fake card numbers and fake transactions, fully simulating a real purchase, without any real money actually changing hands. This lets a team confirm the whole payment flow works correctly before ever handling real customer payments.</p><h2>Why This Matters</h2><p>Testing risky processes like payments directly with real money and real customers would be reckless. A sandbox removes that risk entirely during development and testing.</p><h2>Where Else This Applies</h2><p>Email sending, third-party integrations, and other systems with real-world consequences often offer similar safe sandbox testing modes.</p>", tags: ["Process", "Technology"] },
  { title: "What Is Browser Compatibility, With a Real Example", excerpt: "Not every browser behaves identically. Here's why that matters, with a real example.", content: "<p>Browser compatibility refers to whether a website works correctly across different web browsers, like Chrome, Safari, and Firefox.</p><h2>A Real Example</h2><p>A website might display perfectly in Chrome, but a specific visual effect might look broken or missing in Safari, because different browsers sometimes interpret certain code slightly differently. A careful developer specifically tests across multiple real browsers to catch this kind of inconsistency.</p><h2>Why This Still Matters Today</h2><p>Even though browsers have become more standardized over the years, real differences still exist, especially with newer visual or interactive features.</p><h2>Why This Matters to You</h2><p>If your customers use a mix of different browsers, a site only tested in one browser risks looking broken or unprofessional to a real portion of your actual visitors.</p>", tags: ["Process", "Design"] },
  { title: "What Is Minimum Viable Product (MVP), With a Real Example", excerpt: "This concept helps businesses launch smarter, not just faster. Here's a real explanation.", content: "<p>A Minimum Viable Product is the simplest working version of a product that still delivers real, genuine value to real users.</p><h2>A Real Example</h2><p>Instead of spending a year building every possible feature for a new booking platform before launch, a business might launch first with just the core ability to browse and book appointments, deliberately leaving out extra features like loyalty rewards for a later stage. This lets them start getting real user feedback and real revenue much sooner.</p><h2>Why This Approach Works Well</h2><p>Launching a focused, working core product lets a business learn from real usage and real feedback, then invest further development where it actually matters most, rather than guessing everything upfront.</p><h2>The Honest Trade-Off</h2><p>An MVP deliberately isn't the final, complete vision — it's a genuine, working starting point meant to grow and expand based on real evidence.</p>", tags: ["Business Advice", "Process"] },
  { title: "What Is Graceful Degradation, With a Real Example", excerpt: "This describes how well-built systems fail. Here's a real, understandable example.", content: "<p>Graceful degradation means a system is designed so that if one part fails, the rest still works as well as reasonably possible, rather than the entire thing collapsing completely.</p><h2>A Real Example</h2><p>Imagine a website's live chat widget fails to load due to a technical issue. A well-built site is designed so the rest of the website — browsing, checkout, contact forms — continues working perfectly fine, with only the chat feature temporarily unavailable, rather than the failure of one small feature bringing down the entire site.</p><h2>Why This Matters</h2><p>Real systems will inevitably experience some failures over time. The real engineering question is whether a small failure stays small and contained, or cascades into a much bigger problem.</p><h2>Why This Matters to You</h2><p>A thoughtfully built website limits the real-world impact when something inevitably does go wrong, protecting the overall customer experience.</p>", tags: ["Technology", "Process"] },
  { title: "What Is a Content Management Workflow, With a Real Example", excerpt: "This is about who can do what with your website's content. Here's a real, practical example.", content: "<p>A content workflow defines the process and permissions around how content gets created, reviewed, and published on a website.</p><h2>A Real Example</h2><p>Imagine a growing business where a junior team member can draft new blog posts, but a senior manager must review and approve them before they go live publicly. A proper content workflow enforces exactly this — the junior member simply cannot publish directly, keeping quality control in place as more people join the team.</p><h2>Why This Matters as You Grow</h2><p>A business with only one person managing content doesn't need this structure yet. But as more people get involved, a clear workflow prevents mistakes and keeps a consistent quality standard.</p><h2>Why This Matters to You</h2><p>A CMS genuinely designed with this in mind, like a role-based permission system, lets your team grow and delegate safely, without losing control over what actually gets published.</p>", tags: ["CMS", "Business Advice"] },
];

export async function GET(request: NextRequest) {
  const providedSecret = request.headers.get("x-cron-secret");
  const expectedSecret = process.env.CRON_SECRET;
  if (!expectedSecret || providedSecret !== expectedSecret) {
    return NextResponse.json({ status: "error", message: "Unauthorized." }, { status: 401 });
  }

  await connectToDatabase();

  const founderRole = await Role.findOne({ isFounderRole: true });
  const founder = founderRole ? await User.findOne({ role: founderRole._id }) : null;
  if (!founder) {
    return NextResponse.json({ status: "error", message: "No founder account found." }, { status: 500 });
  }

  let created = 0;
  let skipped = 0;

  for (const post of posts) {
    const slug = slugify(post.title);
    const existing = await BlogPost.findOne({ slug });
    if (existing) {
      skipped++;
      continue;
    }
    await BlogPost.create({
      title: post.title,
      slug,
      excerpt: post.excerpt,
      contentHtml: post.content,
      tags: post.tags,
      publishStatus: "published",
      featured: false,
      createdBy: founder._id,
    });
    created++;
  }

  return NextResponse.json({ status: "ok", created, skipped });
}
